export const errorMessages = {
  BAD_FIRST_NAME_REQUEST: "firstName is required",
  BAD_LAST_NAME_REQUEST: "lastName is required",
  BAD_REQUEST: "Error Message",
  BAD_ID_REQUEST: "ID is wrong",
  BAD_BUNIT_REQUEST: "Bussiness unit is required",
  BAD_LOCATION: "Location is required",
  BAD_CONTACT: "Contact No is required",
  BAD_EMP_ID: "Emp id is required",
  BAD_INSERT_MANY: "Array is required",
  BAD_WEEK_REQUEST: "Week is required",
  BAD_GIVEN_FOR_REQUEST: "Given for is required",
  BAD_GIVEN_BY_REQUEST: "Given by is required",
  BAD_START_DATE_REQUEST: "Start Date is required",
  BAD_END_DATE_REQUEST: "End Date is required",
  BAD_FEEDBACK_REQUEST: "Feedback is required",
  UNAUTHORIZED_ACCESS: "Unauthorized",
  BAD_TOKEN_REQUEST: "Token not found",
  BAD_PASSWORD_REQUEST: "Password is required",
  BAD_PASSWORD_LENGTH_REQUEST: "Password length should be greater than 6",
  BAD_EMAIL_REQUEST: "Email is required",
  BAD_ROLE_REQUEST: "Role is mandatory or wrong",
  BAD_ORIGINALID_REQUEST: "originalId is required",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  NOT_FOUND: "Resource Not Found",
  CONFLICT: "Conflict Occurred",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  VALIDATION_FAILED: "Validation Failed",
  MISSING_REQUIRED_FIELDS: "Missing required fields",
  INVALID_CREDENTIALS: "Invalid email or password",
  USER_EXISTS: "User already exists",
  USER_NOT_FOUND: "User not found",
  TODO_NOT_FOUND: "Todo not found",
  EMAIL_INVALID: "Invalid email format",

  // ✅ Newly added messages for lists/cards:
  BAD_LIST_TITLE: "List title is required",
  BAD_CARD_TITLE: "Card title is required",
  BAD_CARD_DESCRIPTION: "Card description is required",
  BAD_LIST_ID: "List ID is required",
  BAD_CARD_ID: "Card ID is required",
  BAD_USER_ID_REQUEST: "User ID is required",
};


export const status = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

